#!/bin/bash -x
# download zim-tools, libzim, compile tools, and place in $PATH

PREFIX=/opt/iiab
cd $PREFIX
if [ ! -d "$PREFIX/zim-tools" ];then
   git clone https://github.com/openzim/zim-tools
fi
if [ ! -d "$PREFIX/libzim" ];then
   git clone https://github.com/openzim/libzim
fi

apt install -y libzstd-dev
apt install -y libdocopt-dev
apt install -y libgumbo-dev
apt install -y libmagic-dev
apt install -y liblzma-dev
apt install -y libxapian-dev
apt install -y libicu-dev
apt install -y docopt-dev
apt install -y ninja
apt install -y meson
apt install -y cmake
apt install -y pkgconf

cd $PREFIX/libzim
meson . build
ninja -C build
if [ $? -ne 0 ];then
   echo Build of libzim failed. Quitting . . .
   exit 1
fi
ninja -C build install
ldconfig

cd $PREFIX/zim-tools
meson . build
ninja -C build
if [ $? -ne 0 ];then
   echo Build of zim-tools failed. Quitting . . .
   exit 1
fi

cp $PREFIX/zim-tools/build/src/zimbench /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimdiff /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimdump /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimpatch /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimrecreate /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimsearch /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimsplit /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimcheck/zimcheck /usr/local/bin
cp $PREFIX/zim-tools/build/src/zimwriterfs/zimwriterfs /usr/local/bin
